// Copyright 2021 The Autoware Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// \copyright Copyright 2021 The Autoware Foundation
/// \file
/// \brief This file defines the minimal_subscriber_autoware_node class.

#ifndef MINIMAL_SUBSCRIBER_AUTOWARE__MINIMAL_SUBSCRIBER_AUTOWARE_NODE_HPP_
#define MINIMAL_SUBSCRIBER_AUTOWARE__MINIMAL_SUBSCRIBER_AUTOWARE_NODE_HPP_

#include <memory>

#include <minimal_subscriber_autoware/minimal_subscriber_autoware.hpp>

#include <rclcpp/rclcpp.hpp>
#include "std_msgs/msg/string.hpp"

namespace autoware
{
namespace minimal_subscriber_autoware
{

/// \class MinimalSubscriberAutowareNode
/// \brief ROS 2 Node for minimize subscriber.
class MINIMAL_SUBSCRIBER_AUTOWARE_PUBLIC MinimalSubscriberAutowareNode : public rclcpp::Node
{
public:
  /// \brief default constructor, starts driver
  /// \throw runtime error if failed to start threads or configure driver
  explicit MinimalSubscriberAutowareNode(const rclcpp::NodeOptions & options);

  // /// Code generated by Autoware Pkg generator
  // /// \brief print hello
  // /// return 0 if successful.
  // int32_t print_hello() const;

private:
  bool verbose;  ///< whether to use verbose output or not.
  void topic_callback(const std_msgs::msg::String::SharedPtr msg) const;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr subscription_;

};
}  // namespace minimal_subscriber_autoware
}  // namespace autoware

#endif  // MINIMAL_SUBSCRIBER_AUTOWARE__MINIMAL_SUBSCRIBER_AUTOWARE_NODE_HPP_
